# Generated by Django 4.1.3 on 2022-11-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='altitud',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distrito',
            name='ubigeo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
